### ISSUE TITLE
Implement reconciliation logic

### ISSUE THREAD

**Issue by Kn99HN** [Kn99HN/pogger#2]
Parse all the trace files: `trace-*` and carry out the reconciliation logic with vector clock.

Each `Event` type in the trace file should have timestamp = `process_name:path_id:vector_clock`. The vector clocks of each event can be reproduced easily in this case. 

Using the vector clock, it can be determined which event happened before and after. All the paths can be parsed into a Graph with edges, indicating a happened before relationship. This will be useful when we do DFS validation logic later on.

**Comment by joyceluyy** [comment]
Hi Khanh, for this issue, I am planning to take two steps, one is to merge the k sorted array into a linearizable one based on the vector clock, then covert the single array to a tree (this part might be more challenging). Do you think if that is the right path to proceed? Thank you.

**Comment by Kn99HN** [comment]
I think that sounds reasonable! But I think it would be more fruitful for us to use a graph DS in this case since some events might happen concurrently. I think topological sort can come in handy (thou I vaguely remember the algorithm itself).
