### ISSUE TITLE
Implement Checker

### ISSUE THREAD

**Issue by Kn99HN** [Kn99HN/pogger#5]
Checker should takes in an "expectation tree" created from #4 and a "trace tree" produced after reconciliation #2. 

While traverse the expectation tree, we will run the check function for each expectation statement. The possible-match result of each check function will form a search tree, with the height equals to the number of expectation statement ad width dependent on the number of variant statement. 

The Checker should carry out DFS on the search tree, to check if there exists a leaf node that reaches the end of the expectation tree and the trace tree at the same time.

**Comment by joyceluyy** [comment]
I think we can split this issue into two sub-tasks, one is creating check function for each of the expectation statement, and the other to match the expectation tree versus the trace tree.

**Comment by Kn99HN** [comment]
Sounds good 🙌  Do you want to create the GitHub issue for them and link it back to this one?

**Comment by joyceluyy** [comment]
cool will do.
